version: '3.9'

services:
  backend:
    build: 
      dockerfile: dockerfile
      context : ./lru_cache_backend # Path to your Go backend Dockerfile
      target: dev
    ports:
      - "5000:5000" # Map container port 3001 to host port 3001
    volumes:
      - ./lru_cache_backend:/app
    environment:
      - ENVIRONMENT=development

  frontend:
    build: ./lru_cache_frontend # Path to your React frontend Dockerfile
    ports:
      - "3000:3000" # Map container port 3000 to host port 3000
