# Use the official Golang image with version 1.22
FROM golang:1.22-alpine

# Set the working directory for the application
WORKDIR /app

# Copy all application files (excluding Dockerfile) to the working directory
COPY . .

# Install dependencies defined in go.mod
RUN go mod download

# Build the Go binary (replace "main" with the actual name of your main package)
RUN go build -o lru_cache .

# Set the command to execute the built binary
CMD ["./lru_cache"]
